################################### English language #####################################
[en]
languageName = "EN"
languageCode = "en-US"
contentDir = "content/english"
weight = 1
[en.params]
########### footer content ##########
footer_menu_left = "InnerShift"
footer_menu_middle = "Support & Contact"
footer_menu_right = "Legals"
footer_content = "Based in Ireland â€” Serving Clients Worldwide (Online)"
