# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "/blog"
weight = 3

[[main]]
name = "Coaching"
url = "/coaching"
weight = 2

[[main]]
name = "Contact"
url = "/contact"
weight = 5

[[main]]
name = "About"
url = "/about"
weight = 4

# footer menu left
[[footer_left]]
name = "About Cristina"
url = "/about"

[[footer_left]]
name = "Coaching"
url = "/coaching"

[[footer_left]]
name = "InnerShift Newsletter"
url = "/blog"


# footer menu middle
[[footer_middle]]
name = "Book a Session"
url = "https://cal.com/cristina-coffey"

[[footer_middle]]
name = "Contact"
url = "/contact"

# footer menu right
[[footer_right]]
name = "Privacy Policy"
url = "/privacy-policy"

[[footer_right]]
name = "Terms & Conditions"
url = "/terms-conditions"

[[footer_right]]
name = "Disclaimer"
url = "/disclaimer"